import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
// import { AuthProvider } from "@/contexts/authContext";

import { UserDataProvider } from "@/contexts/userDataContext";
import { GradeModalProvider } from "@/contexts/gradeModalContext";
import { SidebarProvider } from "@/components/ui/sidebar";

import LayoutHeader from "@/components/commons/layout/LayoutHeader";
import LayoutNav from "@/components/commons/layout/LayoutNav";
import GradeDialog from "@/components/commons/gradeDialog";

import "./globals.css";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vintage Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <AuthProvider> */}
        <UserDataProvider>
          <SidebarProvider>
            <GradeModalProvider>
              <LayoutNav />
              <div className="flex-1 overflow-auto">
                {/* Nav 외에 유동적으로 크기 맞춤 */}
                <LayoutHeader />
                <main className="h-[calc(100vh - 4rem)] flex-1 bg-gray-50">{children}</main>
                <Toaster position="top-center" />
                <GradeDialog />
              </div>
            </GradeModalProvider>
          </SidebarProvider>
        </UserDataProvider>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
