import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

// import { AuthProvider } from "@/contexts/authContext";
import { ThemeProvider } from "next-themes";
import { SidebarProvider } from "@/components/ui/sidebar";

import LayoutHeader from "@/components/commons/layout/LayoutHeader";
import LayoutNav from "@/components/commons/layout/LayoutNav";
import GradeDialog from "@/components/commons/gradeDialog";
import Wrapper from "@/components/commons/layout/Wrapper";

import "./globals.css";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vintage Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Wrapper>
            {/* <AuthProvider> */}
            <SidebarProvider>
              <LayoutNav />
              <div className="w-full">
                {/* Nav 외에 유동적으로 크기 맞춤 */}
                <LayoutHeader />
                <main>{children}</main>
                <Toaster position="top-center" />
                <GradeDialog />
              </div>
            </SidebarProvider>
            {/* </AuthProvider> */}
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
